### ISSUE TITLE
TODO - Milestone 4 

### ISSUE THREAD

**Issue by roycezhou** [UBC-MDS/DSCI_532_group26#24]
- [x] implement TA's feedback under app.py - Jason
- [x] write reflection file - Siqi 
- [x] trivia (Modify repo description, reply to peer's feedback) - Siqi
- [x] deploy - Bruhat
- [x] optional: doctoring - Siqi and Jason
- [ ] optional: Setup app reviews with Heroku - Bruhat
- [x] Lastly revise README before submission
