### ISSUE TITLE
TODO list - Milestone 2

### ISSUE THREAD

**Issue by roycezhou** [UBC-MDS/DSCI_532_group26#7]
**The TAs will check that you have some issues and PRs in your repo for this milestone**

- [x] Deployment on Heroku

> Deploy your app on Heroku and include the link to your deployed dashboard clearly visible near the top of your README.

> Procfile

> requirements.txt

- [x] Interactive Dash app in Python and Altair

> Dash

> Altair + .ipynb under /reports

- [x] Reflection
- [x] folder structure
- [x] Improve the README
